export const NotificationType = {
  APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
  APPOINTMENT_CONFIRMED: "APPOINTMENT_CONFIRMED",
  APPOINTMENT_CANCELED: "APPOINTMENT_CANCELED",
  APPOINTMENT_REMINDER: "APPOINTMENT_REMINDER",
  APPOINTMENT_UPDATED: "APPOINTMENT_UPDATED",
};
